# Generated by Django 5.1.4 on 2024-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('porcentaje_avance', models.FloatField(verbose_name='Procentaje de avance en Hermes')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del equipo')),
                ('placa', models.IntegerField()),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=45, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=45, verbose_name='Numero serie')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('procedencia', models.CharField(max_length=45, verbose_name='Procedencia')),
                ('uso', models.TextField(verbose_name='Uso del equipo')),
                ('responsable', models.CharField(max_length=75, verbose_name='Responsable')),
                ('numero_odc', models.IntegerField(verbose_name='Numero ODC')),
                ('ano_compra', models.IntegerField(verbose_name='Año de compra')),
                ('proveedor', models.CharField(max_length=45, verbose_name='Proveedor')),
                ('fecha_fabricacion', models.DateField(verbose_name='Fecha de fabricacion')),
                ('vida_util_ano', models.IntegerField()),
                ('fecha_instalacion', models.DateField()),
                ('fin_deprecacion', models.DateField()),
                ('garantia_mes', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=45)),
                ('informacion_faltante', models.TextField()),
                ('observaciones', models.TextField()),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
