# Generated by Django 5.1.4 on 2024-12-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
                ('responsable', models.CharField(max_length=75)),
                ('numero_odc', models.IntegerField()),
                ('ano_compra', models.IntegerField()),
                ('proveedor', models.CharField(max_length=75)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='vida_util_ano',
            field=models.IntegerField(verbose_name='Vida util en años'),
        ),
    ]
