# Generated by Django 5.1.4 on 2024-12-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_insumo_alter_equipo_vida_util_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(upload_to='inventario/images', verbose_name='Imagen'),
        ),
    ]
