# Generated by Django 5.1.4 on 2024-12-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_equipo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
