# Generated by Django 5.1.4 on 2024-12-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_equipo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='proveedor',
            field=models.CharField(max_length=45, null=True, verbose_name='Proveedor'),
        ),
    ]
