# Generated by Django 5.1.4 on 2024-12-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_equipo_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='ano_compra',
            field=models.IntegerField(null=True, verbose_name='Año de compra'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cantidad',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_fabricacion',
            field=models.DateField(null=True, verbose_name='Fecha de fabricacion'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_instalacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fin_deprecacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='garantia_mes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='informacion_faltante',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(max_length=45, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=150, null=True, verbose_name='Nombre del equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_odc',
            field=models.IntegerField(null=True, verbose_name='Numero ODC'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(max_length=45, null=True, verbose_name='Numero serie'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='observaciones',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='placa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='porcentaje_avance',
            field=models.FloatField(null=True, verbose_name='Porcentaje de avance en Hermes'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='procedencia',
            field=models.CharField(max_length=45, null=True, verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='responsable',
            field=models.CharField(max_length=75, null=True, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='uso',
            field=models.TextField(null=True, verbose_name='Uso del equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='vida_util_ano',
            field=models.IntegerField(null=True, verbose_name='Vida util en años'),
        ),
    ]
