# Generated by Django 5.1.4 on 2024-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_equipo_ano_compra_alter_equipo_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_fabricacion',
            field=models.IntegerField(null=True, verbose_name='Fecha de fabricacion'),
        ),
    ]
