# Generated by Django 5.1.4 on 2024-12-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_equipo_fecha_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='vida_util_ano',
            field=models.CharField(max_length=50, null=True, verbose_name='Vida util en años'),
        ),
    ]
