# Generated by Django 5.1.4 on 2024-12-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_equipo_vida_util_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_fabricacion',
            field=models.CharField(max_length=50, null=True, verbose_name='Fecha de fabricacion'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_instalacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fin_deprecacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='garantia_mes',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
