# Generated by Django 5.1.4 on 2024-12-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_equipo_ano_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='numero_odc',
            field=models.CharField(max_length=50, null=True, verbose_name='Numero ODC'),
        ),
    ]
