# Generated by Django 5.1.4 on 2024-12-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_equipo_numero_odc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='placa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
