# Generated by Django 5.1.4 on 2024-12-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_insumo_codigo_alter_insumo_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='proveedor',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
